name: X Auto Tweet Bot

on:
  schedule:
    # 平日朝8:30 (JST) = 23:30 (UTC前日)
    - cron: '30 23 * * 0-4'
    # 平日昼12:30 (JST) = 03:30 (UTC)
    - cron: '30 3 * * 1-5'
    # 平日夜20:30 (JST) = 11:30 (UTC)
    - cron: '30 11 * * 1-5'
    # 土日朝10:30 (JST) = 01:30 (UTC)
    - cron: '30 1 * * 6,0'
    # 土日夜20:30 (JST) = 11:30 (UTC)
    - cron: '30 11 * * 6,0'
  
  # 手動実行用
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tweet bot
      env:
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python tweet_bot.py
