name: X Auto Tweet Bot

on:
  schedule:
    # 平日朝（ダブル実行で確実性UP）
    - cron: '25 23 * * 0-4'  # 8:25実行予定 → 8:30頃投稿
    - cron: '30 23 * * 0-4'  # 8:30実行予定 → 8:35頃投稿（バックアップ）
    
    # 平日昼（ダブル実行で確実性UP）
    - cron: '25 3 * * 1-5'   # 12:25実行予定 → 12:30頃投稿
    - cron: '30 3 * * 1-5'   # 12:30実行予定 → 12:35頃投稿（バックアップ）
    
    # 平日夜（ダブル実行で確実性UP）
    - cron: '25 11 * * 1-5'  # 20:25実行予定 → 20:30頃投稿
    - cron: '30 11 * * 1-5'  # 20:30実行予定 → 20:35頃投稿（バックアップ）
    
    # 土日朝（ダブル実行で確実性UP）
    - cron: '25 1 * * 6,0'   # 10:25実行予定 → 10:30頃投稿
    - cron: '30 1 * * 6,0'   # 10:30実行予定 → 10:35頃投稿（バックアップ）
    
    # 土日夜（ダブル実行で確実性UP）
    - cron: '25 11 * * 6,0'  # 20:25実行予定 → 20:30頃投稿
    - cron: '30 11 * * 6,0'  # 20:30実行予定 → 20:35頃投稿（バックアップ）
  
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tweet bot
      env:
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python tweet_bot.py
